name: Feature Pipeline

on:
  push:
    branches: [ "main" ]  # or any branch you want to test with

jobs:
  test-self-hosted:
    runs-on: self-hosted  # this tells GitHub to use your self-hosted EC2 runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello from self-hosted runner!"
