name: SonarCloud Scan

on:
  push:
    branches:
      - main

      # added

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          organization: hananali0311  # Replace if different on SonarCloud
          projectKey: hananali0311_myhtmlapp
          token: ${{ secrets.SONAR_TOKEN }}
